[SUS-2960] Pre-commit framework

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,6 +3,80 @@ include:
     file: 'ci/scripts/gitlab-ci-susoft.yml'
 
 ##################
+# PRE-COMMIT     #
+##################
+
+# Run pre-commit hooks to enforce code quality
+pre-commit:
+    stage: .pre
+    image: python:3.11-slim
+    before_script:
+        - apt-get update && apt-get install -y git clang-format
+        - pip install pre-commit
+    script:
+        # Only check files that changed in this branch
+        - |
+          if [ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" ]; then
+            # For merge requests, check files changed compared to target branch
+            echo "Checking files changed in merge request..."
+            git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
+            FILES=$(git diff --name-only --diff-filter=d origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME...HEAD)
+          else
+            # For regular branch pushes, check files changed in last commit
+            echo "Checking files changed in last commit..."
+            FILES=$(git diff --name-only --diff-filter=d HEAD~1)
+          fi
+
+          if [ -z "$FILES" ]; then
+            echo "No files to check"
+            exit 0
+          fi
+
+          echo "Files to check:"
+          echo "$FILES"
+
+          # Run pre-commit on changed files
+          pre-commit run --files $FILES
+    rules:
+        - if: '$CI_COMMIT_BRANCH == "master"'
+          when: never
+        - if: '$CI_COMMIT_BRANCH == "appwidevs"'
+          when: never
+        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+          when: on_success
+        - if: '$CI_COMMIT_BRANCH'
+          when: on_success
+
+# Check for Signed-off-by in all commits (only on merge requests)
+check-signoff:
+    stage: .pre
+    image: alpine/git:latest
+    script:
+        - |
+          echo "Checking all commits for Signed-off-by line..."
+          # Get the target branch for the merge request
+          BASE_BRANCH="${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
+          # Check each commit in this merge request
+          UNSIGNED_COMMITS=$(git log origin/${BASE_BRANCH}..HEAD --grep "^Signed-off-by:" --invert-grep --pretty=format:"%h %s")
+          if [ -n "$UNSIGNED_COMMITS" ]; then
+            echo ""
+            echo "The following commits are missing 'Signed-off-by' line:"
+            echo ""
+            echo "$UNSIGNED_COMMITS"
+            echo ""
+            echo "All commits must be signed-off before merging."
+            echo "To fix this, amend each commit with: git commit --amend -s --no-edit"
+            echo "Or rebase and sign all commits: git rebase -i origin/${BASE_BRANCH} -x 'git commit --amend -s --no-edit'"
+            echo ""
+            exit 1
+          else
+            echo "All commits are properly signed-off"
+          fi
+    rules:
+        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+          when: on_success
+
+##################
 # LINUX BUILDS   #
 ##################
 
